backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "screenings"
    label: "Screenings"
    folder: "src/pages/screenings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "screening"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Venue", name: "venue", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Link", name: "link", widget: "string", default: "false"}
      - {label: "Date", name: "date", widget: "datetime"}
